###
GET http://localhost:8080/contacts/6452f758d75850fdbe3032f6 

###
GET https://jadentest02.onrender.com/contacts/6452f758d75850fdbe3032f6
###
GET https://jadentest02.onrender.com/contacts/

###
POST http://localhost:8080/contacts/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bryson",
    "lastName": "Day",
    "email": "brysonday@outlook.com",
    "favoriteColor": "orange",
    "birthday": "01/23/2004"
}

###
DELETE http://localhost:8080/contacts/6456d044b2d1d79dd66bec55 HTTP/1.1

### PUT Contact
PUT http://localhost:8080/contacts/6456cf74c9110acf539c7478 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jacoby",
    "lastName": "Day",
    "email": "fakemail@outlook.com",
    "favoriteColor": "Red",
    "birthday": "10/10/2005"
}
