### GET ONE CONTACT
GET http://localhost:8080/contacts/6452f758d75850fdbe3032f6 

### GET ONE CONTACT
GET https://jadentest02.onrender.com/contacts/6452f758d75850fdbe3032f6
### GET ALL CONTACTS
GET https://jadentest02.onrender.com/contacts/

### CREATE CONTACT
POST http://localhost:8080/contacts/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Day",
    "email": "fake@gmail.com",
    "favoriteColor": "Green",
    "birthday": "07/21/2000"
}

### DELETE CONTACT
DELETE http://localhost:8080/contacts/6456dbe2d5e3521294d62bb6 HTTP/1.1

### PUT CONTACT
PUT http://localhost:8080/contacts/6456dc0bd5e3521294d62bb7 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jason",
    "lastName": "Day",
    "email": "fakemail@outlook.com",
    "favoriteColor": "Blue",
    "birthday": "10/10/2005"
}
